SRC=en
TGT=fr

MAIN_PATH=$PWD
DATA_PATH=$PWD/data
PROC_PATH=$DATA_PATH/processed/$SRC-$TGT
DOMAIN_YELP_SRC_TRAIN_BPE=$PROC_PATH/domain.yelp.train.$SRC
DOMAIN_YELP_DOWNSAMPLED_SRC_TRAIN_BPE=$PROC_PATH/domain.yelp_downsampled.train.$SRC
DOMAIN_YELP_DOWNSAMPLED_LOWERCASED_SRC_TRAIN_BPE=$PROC_PATH/domain.yelp_downsampled_lowercased.train.$SRC
FULL_VOCAB=$PROC_PATH/vocab.en-fr

cat $DOMAIN_YELP_SRC_TRAIN_BPE | shuf -n 14864 > $DOMAIN_YELP_DOWNSAMPLED_SRC_TRAIN_BPE
echo "Binarizing downsampled Yelp EN data..."
rm -f $DOMAIN_YELP_DOWNSAMPLED_SRC_TRAIN_BPE.pth
$MAIN_PATH/preprocess.py $FULL_VOCAB $DOMAIN_YELP_DOWNSAMPLED_SRC_TRAIN_BPE

echo "Binarizing downsampled Yelp EN lowercased data..."
rm -f $DOMAIN_YELP_DOWNSAMPLED_LOWERCASED_SRC_TRAIN_BPE.pth
$MAIN_PATH/convert_to_lowercase.py $DOMAIN_YELP_DOWNSAMPLED_SRC_TRAIN_BPE > $DOMAIN_YELP_DOWNSAMPLED_LOWERCASED_SRC_TRAIN_BPE
$MAIN_PATH/preprocess.py $FULL_VOCAB $DOMAIN_YELP_DOWNSAMPLED_LOWERCASED_SRC_TRAIN_BPE